# Generated by Django 3.1.4 on 2021-03-03 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
                ('heureEvent', models.DateTimeField(verbose_name='programmer le')),
                ('lieuEvent', models.CharField(max_length=30, verbose_name='Lieu evenement:')),
            ],
        ),
        migrations.CreateModel(
            name='PassManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ReservationManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.BigIntegerField(default=0)),
                ('type', models.CharField(choices=[('Pass', 'Pass'), ('Reservation', 'Reservation')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Pass',
            fields=[
                ('ticket_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='concert.ticket')),
            ],
            bases=('concert.ticket',),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('ticket_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='concert.ticket')),
            ],
            bases=('concert.ticket',),
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('tel', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=70, unique=True)),
                ('evenement', models.ManyToManyField(to='concert.Evenement')),
            ],
        ),
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('tel', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=70, unique=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concert.ticket')),
            ],
        ),
        migrations.AddField(
            model_name='evenement',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concert.ticket'),
        ),
        migrations.CreateModel(
            name='Artiste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('tel', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=70, unique=True)),
                ('evenement', models.ManyToManyField(to='concert.Evenement')),
            ],
        ),
    ]
